apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  DB_NAME: mydatabase
  DB_USER: myuser
  DB_HOST: "172.20.160.11"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret-postgres
type: Opaque
data:
  postgres-password: bXlwYXNzd29yZA==